name:               "Jingfeng Yang"
description:        "A student in Peking University"

url:                ""
author:             "thinker3197"
email:              "yjfllpyym@pku.edu.cn"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "JingfengY"
github:             "JingfengYang"
linkedin:           "靖锋-杨-797864172"
facebook:           "yang.jingfeng.33"

disqus_shortname:   "thinker3197"

background:         "w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "CV"
    href:           "/CV-JingfengYang.pdf"
 

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
